apiVersion: v1
kind: Pod
metadata:
  name: node-date-configmap
spec:
  containers:
  - name: node-date
    image: localhost:5002/node-date
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /data
      name: datadir
  volumes:
  - name: datadir
    configMap:
      name: node-configmap
      items:
      - key: datestamp.txt
        path: datestamp.txt